# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Category.create([
  { :id => 2, :name => "Miscellaneous", :user_id => 1, :priority => 0 },
  { :id => 3, :name => "Entertainment", :user_id => 1, :priority => 3 },
  { :id => 4, :name => "Electronics", :user_id => 1, :priority => 4 },
  { :id => 5, :name => "School", :user_id => 1, :priority => 2 },
  { :id => 7, :name => "Work", :user_id => 1, :priority => 5 }
], :without_protection => true )



Comment.create([
  { :id => 3, :user_id => 1, :post_id => 1, :content => "Can I apply?" },
  { :id => 4, :user_id => 5, :post_id => 1, :content => "Yes, you can!" },
  { :id => 5, :user_id => 5, :post_id => 5, :content => "Testing redirect" },
  { :id => 6, :user_id => 1, :post_id => 5, :content => "Mine is an ASUS N56VZ as well. Bro fist!" },
  { :id => 7, :user_id => 1, :post_id => 6, :content => "Just kidding, I deeply dislike his music." }
], :without_protection => true )



Post.create([
  { :id => 1, :title => "Senior Software Developer at Fortumo", :user_id => 1, :topic_id => 26, :content => "Visit http://careers.fortumo.com/estonia/software-developer for more info" },
  { :id => 2, :title => "Junior Software Developer at Fortumo", :user_id => 1, :topic_id => 26, :content => nil },
  { :id => 3, :title => "Android Developer at Fortumo", :user_id => 1, :topic_id => 26, :content => nil },
  { :id => 4, :title => "Carrier Relations Manager at Fortumo", :user_id => 1, :topic_id => 26, :content => nil },
  { :id => 5, :title => "Post your rig!", :user_id => 5, :topic_id => 12, :content => "Mine is an ASUS N56VZ" },
  { :id => 6, :title => "Favourite singer", :user_id => 1, :topic_id => 2, :content => "Who is your favourite singer? Mine is Justin Bieber." }
], :without_protection => true )



Topic.create([
  { :id => 1, :category_id => 2, :user_id => 1, :name => "Cool Stories by Bros" },
  { :id => 2, :category_id => 3, :user_id => 1, :name => "Music" },
  { :id => 4, :category_id => 2, :user_id => 1, :name => "Real estate" },
  { :id => 5, :category_id => 2, :user_id => 1, :name => "Introductions" },
  { :id => 6, :category_id => 2, :user_id => 1, :name => "Outside forums" },
  { :id => 7, :category_id => 2, :user_id => 1, :name => "Funny pictures" },
  { :id => 8, :category_id => 2, :user_id => 1, :name => "Nature" },
  { :id => 9, :category_id => 4, :user_id => 1, :name => "Television" },
  { :id => 10, :category_id => 4, :user_id => 1, :name => "Tablets" },
  { :id => 11, :category_id => 4, :user_id => 1, :name => "Phones" },
  { :id => 12, :category_id => 4, :user_id => 1, :name => "Computers" },
  { :id => 13, :category_id => 4, :user_id => 1, :name => "House hold" },
  { :id => 14, :category_id => 4, :user_id => 1, :name => "Other" },
  { :id => 15, :category_id => 3, :user_id => 1, :name => "Video games" },
  { :id => 16, :category_id => 3, :user_id => 1, :name => "Theatre" },
  { :id => 17, :category_id => 3, :user_id => 1, :name => "Sports" },
  { :id => 18, :category_id => 5, :user_id => 1, :name => "Finals" },
  { :id => 19, :category_id => 5, :user_id => 1, :name => "Teachers" },
  { :id => 20, :category_id => 5, :user_id => 1, :name => "Study-buddies" },
  { :id => 21, :category_id => 5, :user_id => 1, :name => "General chit-chat" },
  { :id => 24, :category_id => 7, :user_id => 1, :name => "General" },
  { :id => 25, :category_id => 7, :user_id => 1, :name => "Corporations" },
  { :id => 26, :category_id => 7, :user_id => 1, :name => "Job offers" }
], :without_protection => true )



User.create([
  { :id => 1, :first_name => "Taavi", :last_name => "Kala", :username => "xenover", :email => "xenover@gmail.com", :birthday => "1991-10-28", :password_hash => "$2a$10$76H.gcJcd5GkzILZh4TktevpU3orZ9n6YKBhxRIgV2xrpqkWIdnIu", :password_salt => "$2a$10$76H.gcJcd5GkzILZh4Tkte", :about => nil, :authority_level => 2 },
  { :id => 4, :first_name => "Agnes", :last_name => "Rikk", :username => "agnesaksy", :email => "agnesasky@gmail.com", :birthday => "1992-05-24", :password_hash => "$2a$10$2oQtAjV7dN8bTIuXOuCiS.fDu4xL8.krFe0VZ0Dgp0khbt77gX/3y", :password_salt => "$2a$10$2oQtAjV7dN8bTIuXOuCiS.", :about => "Pretty schmexy gurl", :authority_level => 0 },
  { :id => 5, :first_name => "Taavi", :last_name => "Kala", :username => "taavik", :email => "kilu12@hot.ee", :birthday => "1991-10-28", :password_hash => "$2a$10$vB8sCc2VBn306A8AfkAjq.Fa3LeCzo0Qn6xmJ82PDtIFkzoV5Suqm", :password_salt => "$2a$10$vB8sCc2VBn306A8AfkAjq.", :about => "Nuthin' much", :authority_level => 0 }
], :without_protection => true )


